### ISSUE TITLE
Input lag optimization?

### ISSUE THREAD

**Issue by Tatsuya79** [byuu/bsnes#52]
It's an old controversial subject that wasn't relevant with higan but maybe now it makes sense in bsnes?
Testing a game by keeping a direction down on the gamepad and using the "next frame" hotkey I can count 4 frames before seeing a reaction in SMW (instead of 3 in snes9x or Mesen-S).

Is it possible to reduce that?
[This is the way it was done in the libretro core for reference.](https://github.com/Tatsuya79/bsnes-libretro/pull/1/files)

A similar observation with the SGB: 6 frames in super mario land can perhaps be reduced?

**Comment by byuu** [comment]
Can you prove this reduces lag? bsnes doesn't work like other emulators, please see:

https://github.com/byuu/bsnes/blob/master/bsnes/target-bsnes/input/input.cpp#L271
https://github.com/byuu/bsnes/blob/master/bsnes/target-bsnes/program/platform.cpp#L269
https://github.com/byuu/bsnes/blob/master/bsnes/sfc/controller/gamepad/gamepad.cpp#L35
https://github.com/byuu/bsnes/blob/master/bsnes/sfc/cpu/io.cpp#L17

The way it works is that whenever the SNES core reads the controllers, if they haven't polled the real hardware keyboard/gamepads in the last N milliseconds (default is 5), it polls them immediately. This happens whether we have exited the core or not.

bsnes-mercury is from bsnes v073, which I released in 2010, nine years ago. It likely used a different strategy where that patch may have helped, at least with libretro.

If you can show me evidence that your approach decreases latency in bsnes v108, I will merge this change. Thank you ^-^

**Comment by Tatsuya79** [comment]
I can't investigate more right now as I don't own a modern phone with an high framerate recording mode. Hope I can get one soon though as it's interesting for many other tests.
In the meantime, if anyone feels like doing it they're welcome.

**Comment by byuu** [comment]
Been a week with no input.

Tatsuya, RetroArch developers, or anyone else reading this: I'm more than happy to apply an input lag fix if there is demonstrable evidence it actually fixes lag. Please reopen the task with such evidence should it present itself and I promise that I will merge the changes.

**Comment by realnc** [comment]
Not sure if this helps anything, since it's just an unscientific test of two instances of Retroarch running next to each other. On the left is the snes9x core, on the right it's the bsnes hd (version 110) core.

Run-ahead is disabled. Vulkan driver is used, with swapchain images set to 1. VSYNC is disabled. This is running on Linux.

http://83.212.109.87/~realnc/vid/snes9x_vs_bsneshd.mp4

The Snes9x core is always registering the button press sooner.

**Comment by Tatsuya79** [comment]
I did that same test on win7 and I got snes9x RA faster than bsnes RA on almost all frames too.
Same results with snes9x RA vs bsnes stand-alone (47/50 times snes9x is faster).

Strangely enough snes9x stand-alone vs bsnes stand-alone were similar despite checking snes9x "lag reduction" setting.
I'm using opengl for everything vsync enabled, gsync disabled.

**Comment by Tatsuya79** [comment]
[This change did not help for RA.](https://github.com/byuu/bsnes/commit/e78aca34b9454328b2de445806a28076ca21023b#diff-2f2cca333b4315b374c290fbdc6e2059R126)

But replacing it with 
```cpp
if(vcounter() == vdisp()-1)
```
works but will make the last line rendered in the next frame.

**Comment by Tatsuya79** [comment]
fixed in https://github.com/byuu/bsnes/commit/fb95d5b59f2661b698987072c0545620ec686751
:+1:

**Comment by robertos677** [comment]
> Can you prove this reduces lag? bsnes doesn't work like other emulators, please see:
> 
> https://github.com/byuu/bsnes/blob/master/bsnes/target-bsnes/input/input.cpp#L271
> https://github.com/byuu/bsnes/blob/master/bsnes/target-bsnes/program/platform.cpp#L269
> https://github.com/byuu/bsnes/blob/master/bsnes/sfc/controller/gamepad/gamepad.cpp#L35
> https://github.com/byuu/bsnes/blob/master/bsnes/sfc/cpu/io.cpp#L17
> 
> The way it works is that whenever the SNES core reads the controllers, if they haven't polled the real hardware keyboard/gamepads in the last N milliseconds (default is 5), it polls them immediately. This happens whether we have exited the core or not. Exiting the core does nothing in bsnes v108. Since gamepads are almost always polled once per frame, that means it's immediate. The 5ms check is only to prevent a pathological edge-case demo from reading the gamepads in an infinite loop, as polling real hardware is costly. In practice it will be instant for 100% (not even 99.99%) of official SNES games.

Hi @byuu 

The input latency the "lagfix" patch removes is unrelated to input caching. It's a product of syncing (blocking) on video. Even if the emulator polled the host directly every time the emulated system did, the problem would still exist.

Let me demonstrate. Imagine we have a simple loop

```
while true; do
    emulateFrame();
    drawToScreen();
done
```
emulateFrame() runs the emulator and returns at a given scanline
drawToScreen() outputs a frame, blocking (syncing) when there is already a frame in the host video buffer

Four cycles for a game with a one-frame response and which polls for input during vblank might look like this:
```
emulator.runFrame()
video.drawFrame() <--- user presses START here
emulator.runFrame() <--- input read here
video.drawFrame()
emulator.runFrame()
video.drawFrame() <--- with LAGFIX: reaction here
emulator.runFrame() 
video.drawFrame() <--- without LAGFIX: reaction here
```
As you can see, with the lagfix patch applied, we get a reaction one frame earlier. Even if a game polls outside of the blanking period, there is still a small, albeit limited reduction in input latency.

That's because, with the lagfix, emulation is never ahead and almost* always behind, while video output and its timing remains unchanged. This translates to less input latency because we're narrowing the gap between input reads and output.

To reiterate: video output and its timing, is *unchanged*, with or without the lag fix. But with the lagfix, inputs are read later.

You can also think of it as more closely syncing the host display to the state of the emulator by suspending execution as soon as a full frame is generated, allowing the display to "catch up" sooner.

I hope this clears things up.

*: the exception being the very first call to the main loop for up to 224 or 239 emulated scan lines. For the rest of the time, it's behind.

**Comment by robertos677** [comment]
Also, the latest version of the "lagfix" is slightly more sophisticated. It now relies on NMI to handle the possibility of bit 2 of $2133 (overscan mode) being set mid-frame. Whether this covers every conceivable corner case, I'm not sure. Byuu is far more qualified than me to speak to this.

There is, I think, a further opportunity to exit early if overscan mode is set before scanline 224 but then turned off before line 240, but I think that's more trouble than its worth.
